### ISSUE TITLE
Mobile / Touch-friendly?

### ISSUE THREAD

**Issue by chenrycommit** [simeydotme/jQuery-ui-Slider-Pips#48]
Any plans to support mobile?  This is a great project, unfortunately it doesn't seem to work on any mobile devices.

**Comment by simeydotme** [comment]
Thanks for the contribution, @chenrycommit :D

Actually; it is fully functional for mobile... thanks for your interest. I believe what you're referring to is the jQuery UI Slider (from jQueryUI) has no touch event support. You can fix this with [jQuery UI touch punch](http://touchpunch.furf.com/) ... if you desire a touch event instead of a click event on the labels I would suggest you edit the code yourself; I wouldn't want the change to affect other people's mobile apps :smile: 

https://github.com/simeydotme/jQuery-ui-Slider-Pips/issues/34
